[package]
name = "hartex-rust"
version = "0.2.0"
authors = ["kanishkarj"]
edition = "2018"

[build-dependencies]
cc = "1.0.28"

[dependencies]
cortex-m-semihosting = "0.3.2"
cortex-m = {version="0.5.8", features=["inline-asm","const-fn"]}
cortex-m-rt = "*"

[features]
tasks_32 = []
tasks_16 = []
tasks_8 = []

default = []

[lib]
test = false
bench = false