[package]
name = "cortexm-threads"
version = "0.1.0"
authors = ["nk"]
edition = "2018"

[build-dependencies]
cc = "1.0.28"

[dependencies]
cortex-m-semihosting = "0.3.2"
cortex-m = {version="0.5.8", features=["inline-asm","const-fn"]}
cortex-m-rt = "*"